In [1]:
import pandas as pd
import pyrfume
from pyrfume import keller
from pyrfume.odorants import from_cids

In [2]:
# Loads the raw data from 12868_2016_287_MOESM1_ESM.xlsx
raw = keller.load_raw_bmc_data()
raw.head()

,C.A.S.,Catalogue #*,CID,Odor,Odor dilution,Subject # (this study),Subject # (DREAM challenge),Gender,"Race\n (""unknown"" indicates\n that the subject did not\n wish to specify)",Ethnicity,...,ACID,WARM,MUSKY,SWEATY,AMMONIA/URINOUS,DECAYED,WOOD,GRASS,FLOWER,CHEMICAL
0,2257-09-2,W401404,16741,2-Phenylethyl isothiocyanate,"1/1,000",1,1.0,M,Black,Non-Hispanic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2257-09-2,W401404,16741,2-Phenylethyl isothiocyanate,"1/100,000",1,1.0,M,Black,Non-Hispanic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2442-10-6,W358207,17121,1-Octen-3-yl acetate,"1/1,000",1,1.0,M,Black,Non-Hispanic,...,NaN,NaN,NaN,NaN,NaN,63.0,NaN,NaN,NaN,NaN
3,2442-10-6,W358207,17121,1-Octen-3-yl acetate,"1/100,000",1,1.0,M,Black,Non-Hispanic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2530-10-1,W352705,520191,"3-Acetyl-2,5-dimethylthiophene","1/100,000",1,1.0,M,Black,Non-Hispanic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
behavior = keller.format_bmc_data(raw,
                                  only_dream_subjects=False,  # Whether to only keep DREAM subjects
                                  only_dream_descriptors=False,  # Whether to only keep DREAM descriptors
                                  only_dream_molecules=False)  # Whether to only keep DREAM molecules))
behavior.head()

Subject                             1    2    3    4    5   6    7    8    9   \
Descriptor CID Dilution Replicate
Acid       126 -3.0     0          0.0  0.0  0.0  0.0  NaN NaN  0.0  0.0  NaN
               -1.0     0          0.0  0.0  NaN  0.0  0.0 NaN  0.0  0.0  0.0
           176 -7.0     0          NaN  NaN  NaN  0.0  NaN NaN  NaN  NaN  NaN
               -5.0     0          NaN  0.0  0.0  NaN  0.0 NaN  NaN  0.0  NaN
           177 -5.0     0          0.0  0.0  NaN  0.0  NaN NaN  0.0  NaN  NaN

Subject                             10  ...    46   47   48   49   50   51  \
Descriptor CID Dilution Replicate       ...
Acid       126 -3.0     0          0.0  ...   NaN  NaN  0.0  0.0  0.0  0.0
               -1.0     0          0.0  ...  32.0  0.0  NaN  0.0  0.0  0.0
           176 -7.0     0          NaN  ...   NaN  NaN  1.0  NaN  0.0  0.0
               -5.0     0          NaN  ...   NaN  NaN  NaN  NaN  0.0  NaN
           177 -5.0     0          0.0  ...   0.0  NaN  NaN  0.0  0.0  0.0

Subject                             52   53   54   55
Descriptor CID Dilution Replicate
Acid       126 -3.0     0          NaN  NaN  NaN  0.0
               -1.0     0          1.0  0.0  0.0  0.0
           176 -7.0     0          NaN  NaN  NaN  NaN
               -5.0     0          NaN  NaN  0.0  NaN
           177 -5.0     0          2.0  0.0  NaN  NaN

[5 rows x 55 columns]

In [5]:
cids = behavior.index.unique(level='CID')
molecules = pd.DataFrame(from_cids(cids))

HBox(children=(FloatProgress(value=0.0, max=5.0), HTML(value='')))

Retrieving 0 through 99
Retrieving 100 through 199
Retrieving 200 through 299
Retrieving 300 through 399
Retrieving 400 through 479

In [6]:
molecules.set_index('CID').to_csv('molecules.csv')

In [7]:
behavior.index = behavior.index.reorder_levels([1, 0, 2, 3]) # Put CID first

In [8]:
behavior = behavior.sort_index(level=0) # Sort by CID ascending

In [9]:
behavior.to_csv('behavior.csv')